### ISSUE TITLE
Add option for Stable release

### ISSUE THREAD

**Issue by kjenney** [chef-partners/dcos-cookbook#5]
The Early Access build script is used to deploy the cluster. In production I prefer to use stable:

https://downloads.dcos.io/dcos/stable/dcos_generate_config.sh

It would be nice to attribute this.

**Comment by jjasghar** [comment]
@kjenney i think https://github.com/chef-partners/dcos-cookbook/pull/6 is what you want? If so please comment back here, and i can push out a new version.

**Comment by mastermindg** [comment]
Yes please!

**Comment by jjasghar** [comment]
🤘

**Comment by jjasghar** [comment]
Pushed to the supermarket: https://supermarket.chef.io/cookbooks/dcos
